<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('users')->delete();

        \DB::table('users')->insert(array (
            0 =>
            array (
                'id' => 1,
                'first_name' => 'Gregory',
                'last_name' => 'Gonzalez',
                'unit_id' => 1242,
                'resident_status_id' => 1,
                'account_approved' => 1,
                'approved_by_user_id' => 1,
                'board_member' => 0,
                'administrator' => 1,
                'active' => 1,
                'gate_code' => '6956',
                'profile_picture' => 'private/headshot_uploads/1.jpg',
                'mobile_phone' => '602-245-6956',
                'home_phone' => NULL,
                'work_phone' => NULL,
                'email' => 'gregory_gonzalez@sbcglobal.net',
                'password' => '$2y$10$PNtGg2pR8pXRsZ1CW80sJedZigWOs/zJOZh1VhgLqN2zCRvuAwfvW',
                'remember_token' => NULL,
                'created_at' => '2019-05-29 11:27:38',
                'updated_at' => '2019-05-29 11:27:38',
                'last_login_at' => NULL,
                'password_expires_at' => '2021-08-29 11:27:35',
                'email_verified_at' => '2019-05-29 11:27:38',
            ),
            1 =>
            array (
                'id' => 2,
                'first_name' => 'Elisa',
                'last_name' => 'Gonzalez',
                'unit_id' => 1242,
                'resident_status_id' => 1,
                'account_approved' => 1,
                'approved_by_user_id' => 1,
                'board_member' => 0,
                'administrator' => 0,
                'active' => 1,
                'gate_code' => '6956',
                'profile_picture' => 'private/headshot_uploads/2.jpg',
                'mobile_phone' => '910-691-9895',
                'home_phone' => NULL,
                'work_phone' => NULL,
                'email' => 'elisagonzalez8842@gmail.com',
                'password' => '$2y$10$RoxzqsSkZaPlE.5EAScZq.lzmX7n2CzMxO2WRYsVUKxelp8DVm6HO',
                'remember_token' => NULL,
                'created_at' => '2019-05-29 11:27:38',
                'updated_at' => '2019-05-29 11:27:38',
                'last_login_at' => NULL,
                'password_expires_at' => '2021-08-29 11:27:35',
                'email_verified_at' => '2019-05-29 11:27:38',
            ),
            2 =>
            array (
                'id' => 3,
                'first_name' => 'Cameron',
                'last_name' => 'Murillo',
                'unit_id' => 1201,
                'resident_status_id' => 1,
                'account_approved' => 1,
                'approved_by_user_id' => 1,
                'board_member' => 1,
                'administrator' => 0,
                'active' => 1,
                'gate_code' => '3544',
                'profile_picture' => 'private/headshot_uploads/3.jpg',
                'mobile_phone' => '530-828-3544',
                'home_phone' => NULL,
                'work_phone' => NULL,
                'email' => 'kennyakacameron@aim.com',
                'password' => '$2y$10$2Hp/9lKD5XNjFANBSjBWhelP/U9zngx3RViS1dVzPMcVQ8Wfe3oDS',
                'remember_token' => NULL,
                'created_at' => '2019-05-29 11:27:38',
                'updated_at' => '2019-08-07 20:20:48',
                'last_login_at' => NULL,
                'password_expires_at' => '2019-08-29 11:27:35',
                'email_verified_at' => '2019-05-29 11:27:38',
            ),
            3 =>
            array (
                'id' => 4,
                'first_name' => 'Winnie',
                'last_name' => 'Kaplan',
                'unit_id' => 1091,
                'resident_status_id' => 1,
                'account_approved' => 1,
                'approved_by_user_id' => 1,
                'board_member' => 1,
                'administrator' => 0,
                'active' => 1,
                'gate_code' => '7256',
                'profile_picture' => 'private/headshot_uploads/4.jpg',
                'mobile_phone' => '310-500-7256',
                'home_phone' => NULL,
                'work_phone' => NULL,
                'email' => 'winniemyrealtor@gmail.com',
                'password' => '$2y$10$4v5jYK3Xy0e/6PjvMMmQlOyv7G4dYEYCFGHImFGhOmaQvW9M3H2t6',
                'remember_token' => NULL,
                'created_at' => '2019-05-29 11:27:38',
                'updated_at' => '2019-08-07 20:28:04',
                'last_login_at' => NULL,
                'password_expires_at' => '2019-08-29 11:27:35',
                'email_verified_at' => '2019-05-29 11:27:38',
            ),
            4 =>
            array (
                'id' => 5,
                'first_name' => 'Steve',
                'last_name' => 'Kaplan',
                'unit_id' => 1091,
                'resident_status_id' => 1,
                'account_approved' => 1,
                'approved_by_user_id' => 1,
                'board_member' => 0,
                'administrator' => 0,
                'active' => 1,
                'gate_code' => '8108',
                'profile_picture' => 'private/headshot_uploads/5.jpg',
                'mobile_phone' => '310-926-8108',
                'home_phone' => NULL,
                'work_phone' => NULL,
                'email' => 'stevek@writechoices.com',
                'password' => '$2y$10$f21vnnswySf0pJyVb./7KORx6btXPluNb3sw7jI7MnL/f88CzUieC',
                'remember_token' => NULL,
                'created_at' => '2019-05-29 11:27:38',
                'updated_at' => '2019-08-07 20:36:14',
                'last_login_at' => NULL,
                'password_expires_at' => '2019-08-29 11:27:35',
                'email_verified_at' => '2019-05-29 11:27:38',
            ),
            5 =>
            array (
                'id' => 6,
                'first_name' => 'Steven',
                'last_name' => 'Preston',
                'unit_id' => 1327,
                'resident_status_id' => 1,
                'account_approved' => 1,
                'approved_by_user_id' => 1,
                'board_member' => 1,
                'administrator' => 0,
                'active' => 1,
                'gate_code' => '5561',
                'profile_picture' => 'private/headshot_uploads/6.jpg',
                'mobile_phone' => '518-888-5561',
                'home_phone' => NULL,
                'work_phone' => NULL,
                'email' => 'steven.preston@conferencedirect.com',
                'password' => '$2y$10$YJCjA2okqFpdrchZIGrTR.FYoror1JgfDMlubgCcujPJY9sVq.3ea',
                'remember_token' => NULL,
                'created_at' => '2019-05-29 11:27:38',
                'updated_at' => '2019-08-07 20:39:51',
                'last_login_at' => NULL,
                'password_expires_at' => '2019-08-29 11:27:35',
                'email_verified_at' => '2019-05-29 11:27:38',
            ),
            6 =>
            array (
                'id' => 7,
                'first_name' => 'Ricardo',
                'last_name' => 'Flores',
                'unit_id' => 1350,
                'resident_status_id' => 1,
                'account_approved' => 1,
                'approved_by_user_id' => 1,
                'board_member' => 0,
                'administrator' => 0,
                'active' => 1,
                'gate_code' => '0482',
                'profile_picture' => 'private/headshot_uploads/7.jpg',
                'mobile_phone' => '480-254-0482',
                'home_phone' => NULL,
                'work_phone' => NULL,
                'email' => 'ricardoflores0609@gmail.com',
                'password' => '$2y$10$h3Qe198I.iVgTJYCmvzfL.Jzga8Y2kBeubM9Z5wHHyulzSAOigDL2',
                'remember_token' => NULL,
                'created_at' => '2019-05-29 11:27:38',
                'updated_at' => '2019-08-07 20:50:23',
                'last_login_at' => NULL,
                'password_expires_at' => '2019-08-29 11:27:35',
                'email_verified_at' => '2019-05-29 11:27:38',
            ),
        ));


    }
}
